### ISSUE TITLE
miRipples missing from v0.0.1

### ISSUE THREAD

**Issue by geoffroymontel** [v7b1/mi-UGens#12]
Hello

Thanks for this port ! It's an awesome addition to SC !
I downloaded the release v0.0.1 for MacOSX and it looks like MiRipples is missing.
I'm getting this error when running the examples :
exception in GraphDef_Recv: UGen 'MiRipples' not installed.

all the best

Geoffroy

**Comment by v7b1** [comment]
Hi @geoffroymontel  - yes, there's a problem with the automatic built of MiRipples on mac. Linux and Windows builts seem to be fine. MiRipples depends on some c++11 features and I guess, here's the problem. Will be fixed with the next update. In the meantime, you could use MiRipples form [here](https://vboehm.net/maxobjects/vb.mi-objects.zip).
Thanks!

**Comment by geoffroymontel** [comment]
Thanks a lot for the update and the build !!
